# Generated by Django 5.2 on 2026-05-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asiento',
            old_name='estado',
            new_name='estado_asiento',
        ),
        migrations.RenameField(
            model_name='funcion',
            old_name='fecha_funcion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='funcion',
            old_name='hora_fin',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre_sala',
            field=models.CharField(max_length=80),
        ),
    ]
