# Generated by Django 5.2 on 2026-05-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_rename_estado_asiento_estado_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/posters/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='formato',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
