# Generated by Django 5.2.14 on 2026-05-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('genero', models.CharField(max_length=80)),
                ('sinopsis', models.TextField()),
                ('duracion', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=30)),
                ('idioma', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_estreno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('tipo_sala', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_funcion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
                ('tipo_asiento', models.CharField(default='Normal', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.sala')),
            ],
            options={
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
