# Generated by Django 5.2 on 2026-05-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='nivel_acceso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ci',
        ),
        migrations.AddField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(default='Administrador', max_length=80),
        ),
        migrations.AddField(
            model_name='administrador',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
