# Generated by Django 5.2 on 2026-05-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_rename_estado_asiento_estado_asiento_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketvirtual',
            name='detalle_venta',
        ),
        migrations.RemoveField(
            model_name='ticketvirtual',
            name='venta',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='estado',
            new_name='estado_pago',
        ),
        migrations.RenameField(
            model_name='promocion',
            old_name='porcentaje_descuento',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='cantidad_entradas',
            new_name='cantidad_boletos',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='codigo_control',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='nit_ci',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='numero_comprobante',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='funcion',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(default='No definido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_boleto', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo_qr', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_boleto', models.CharField(default='emitido', max_length=30)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.asiento')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.funcion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'unique_together': {('funcion', 'asiento')},
            },
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='TicketVirtual',
        ),
    ]
